const PLANTDATA = [
  {
    "id": 238,
    "title": "minim",
    "description": "nulla dolor eu nulla duis labore consectetur magna ipsum id anim duis qui esse fugiat veniam aliqua labore magna proident Lorem ipsum reprehenderit laboris sit ex anim est eiusmod ad occaecat esse incididunt nostrud fugiat magna dolor reprehenderit labore pariatur",
    "price": 880,
    "currency": "₹",
    "category": "organic",
    "img": "plant8.png",
    "size": "id",
    "plantType": "excepteur",
    "height": 27,
    "humidity": 64,
    "waterEvery": "7 hr",
    "unit": 3,
    "rating": 1
  },
  {
    "id": 947,
    "title": "consectetur",
    "description": "aute labore anim non elit aute ullamco magna labore ut irure voluptate Lorem consequat ea ipsum laboris mollit proident dolore id proident ex culpa nulla veniam quis ullamco voluptate nisi aliquip id est tempor cillum aliquip nisi do sint consequat",
    "price": 626,
    "currency": "₹",
    "category": "organic",
    "img": "plant16.png",
    "size": "officia",
    "plantType": "mollit",
    "height": 26,
    "humidity": 71,
    "waterEvery": "7 hr",
    "unit": 5,
    "rating": 3
  },
  {
    "id": 103,
    "title": "esse",
    "description": "proident ullamco occaecat qui aliquip adipisicing amet amet amet duis reprehenderit ad aute ea ipsum irure cupidatat nulla esse in velit eu ex laboris est sit proident nulla laboris est veniam qui proident reprehenderit ullamco id amet ea reprehenderit aliquip",
    "price": 319,
    "currency": "₹",
    "category": "organic",
    "img": "plant5.png",
    "size": "quis",
    "plantType": "voluptate",
    "height": 26,
    "humidity": 69,
    "waterEvery": "14 hr",
    "unit": 829,
    "rating": 3
  },
  {
    "id": 763,
    "title": "deserunt",
    "description": "Lorem pariatur consequat nostrud ullamco cillum tempor in aliqua ex excepteur culpa Lorem consectetur ad elit culpa irure sint adipisicing excepteur culpa incididunt mollit proident cillum in aliquip aliqua aliqua amet deserunt pariatur labore ex exercitation deserunt aliquip cupidatat reprehenderit",
    "price": 530,
    "currency": "₹",
    "category": "organic",
    "img": "plant18.png",
    "size": "enim",
    "plantType": "sit",
    "height": 6,
    "humidity": 89,
    "waterEvery": "21 hr",
    "unit": 8,
    "rating": 2
  },
  {
    "id": 801,
    "title": "in",
    "description": "aliqua dolore mollit cupidatat qui ad officia veniam amet sint labore sunt enim incididunt consequat nostrud eiusmod in velit nulla duis ullamco consequat commodo in eiusmod sit labore sunt tempor cillum esse id sunt consequat consectetur culpa aliquip ullamco eiusmod",
    "price": 802,
    "currency": "₹",
    "category": "organic",
    "img": "plant14.png",
    "size": "veniam",
    "plantType": "esse",
    "height": 17,
    "humidity": 70,
    "waterEvery": "12 hr",
    "unit": 1260,
    "rating": 5
  },
  {
    "id": 38,
    "title": "occaecat",
    "description": "reprehenderit sint officia nisi ad amet ullamco occaecat aute commodo labore commodo esse mollit ipsum cillum enim exercitation adipisicing tempor elit est culpa qui minim eu ex exercitation consequat nostrud consectetur commodo deserunt aliqua est incididunt reprehenderit eu fugiat minim",
    "price": 240,
    "currency": "₹",
    "category": "organic",
    "img": "plant16.png",
    "size": "incididunt",
    "plantType": "Lorem",
    "height": 8,
    "humidity": 68,
    "waterEvery": "24 hr",
    "unit": 3,
    "rating": 1
  },
  {
    "id": 502,
    "title": "consectetur",
    "description": "nulla ea nisi voluptate dolore deserunt ea Lorem fugiat in anim cillum reprehenderit sint ipsum dolore cupidatat minim anim deserunt ad commodo esse sint dolor fugiat non pariatur proident velit eiusmod amet non eiusmod mollit ipsum excepteur do in cillum",
    "price": 299,
    "currency": "₹",
    "category": "organic",
    "img": "plant14.png",
    "size": "minim",
    "plantType": "cillum",
    "height": 14,
    "humidity": 86,
    "waterEvery": "23 hr",
    "unit": 5,
    "rating": 2
  },
  {
    "id": 642,
    "title": "voluptate",
    "description": "reprehenderit commodo nostrud commodo nostrud aliquip irure et exercitation ea sit nostrud dolor commodo amet est enim cupidatat eiusmod quis tempor est deserunt dolore cillum nisi mollit exercitation do fugiat minim veniam nisi mollit elit dolore nostrud duis occaecat proident",
    "price": 447,
    "currency": "₹",
    "category": "organic",
    "img": "plant14.png",
    "size": "non",
    "plantType": "veniam",
    "height": 25,
    "humidity": 92,
    "waterEvery": "12 hr",
    "unit": 7,
    "rating": 5
  },
  {
    "id": 745,
    "title": "elit",
    "description": "labore do laborum nostrud qui qui irure excepteur cupidatat duis duis duis consequat et voluptate aute exercitation do ad minim velit adipisicing cupidatat Lorem enim quis nisi pariatur ex elit sit Lorem esse Lorem dolore magna deserunt occaecat id consequat",
    "price": 607,
    "currency": "₹",
    "category": "organic",
    "img": "plant6.png",
    "size": "dolore",
    "plantType": "eu",
    "height": 24,
    "humidity": 64,
    "waterEvery": "2 hr",
    "unit": 1387,
    "rating": 2
  },
  {
    "id": 723,
    "title": "non",
    "description": "ut consectetur officia non cillum aliqua ipsum ex ut Lorem voluptate culpa nulla mollit ut proident culpa esse aliqua sint irure aute culpa tempor consequat ipsum proident Lorem labore deserunt velit esse sint deserunt minim occaecat deserunt enim quis eu",
    "price": 880,
    "currency": "₹",
    "category": "organic",
    "img": "plant16.png",
    "size": "duis",
    "plantType": "ullamco",
    "height": 30,
    "humidity": 95,
    "waterEvery": "19 hr",
    "unit": 12,
    "rating": 2
  },
  {
    "id": 138,
    "title": "cillum",
    "description": "proident nisi laborum cillum ipsum ex eiusmod tempor Lorem proident commodo Lorem esse irure culpa sit nulla consequat anim minim deserunt Lorem ad irure dolore exercitation eu eu esse adipisicing amet cillum aute sunt dolor amet consectetur reprehenderit ut ex",
    "price": 606,
    "currency": "₹",
    "category": "organic",
    "img": "plant4.png",
    "size": "magna",
    "plantType": "voluptate",
    "height": 14,
    "humidity": 96,
    "waterEvery": "7 hr",
    "unit": 492,
    "rating": 1
  },
  {
    "id": 11,
    "title": "quis",
    "description": "cupidatat sunt irure cillum voluptate occaecat non id culpa do irure ullamco eiusmod amet dolore duis labore cupidatat minim dolor aliquip irure nisi cillum ipsum labore Lorem eiusmod consectetur pariatur et amet elit mollit proident eiusmod amet ullamco adipisicing reprehenderit",
    "price": 805,
    "currency": "₹",
    "category": "organic",
    "img": "plant8.png",
    "size": "exercitation",
    "plantType": "nisi",
    "height": 9,
    "humidity": 85,
    "waterEvery": "24 hr",
    "unit": 1181,
    "rating": 3
  },
  {
    "id": 35,
    "title": "cupidatat",
    "description": "dolore anim est et mollit nulla proident quis non esse elit sint fugiat quis aliqua Lorem consectetur non ea laborum nisi anim labore elit laboris irure irure dolor sunt sit non sit exercitation do dolor est deserunt velit nisi cupidatat",
    "price": 944,
    "currency": "₹",
    "category": "organic",
    "img": "plant4.png",
    "size": "eu",
    "plantType": "et",
    "height": 24,
    "humidity": 63,
    "waterEvery": "21 hr",
    "unit": 1388,
    "rating": 5
  },
  {
    "id": 699,
    "title": "Lorem",
    "description": "ad qui sunt laboris reprehenderit nisi amet commodo enim laborum sint proident occaecat dolore eiusmod aliquip voluptate amet deserunt aute minim anim deserunt ipsum enim do eiusmod occaecat dolor nulla nulla esse cupidatat duis id labore occaecat cupidatat elit aute",
    "price": 310,
    "currency": "₹",
    "category": "organic",
    "img": "plant8.png",
    "size": "ea",
    "plantType": "reprehenderit",
    "height": 4,
    "humidity": 74,
    "waterEvery": "5 hr",
    "unit": 555,
    "rating": 4
  },
  {
    "id": 853,
    "title": "veniam",
    "description": "Lorem cupidatat pariatur laborum nostrud in ut Lorem aliqua Lorem laborum et dolore quis adipisicing minim ea reprehenderit veniam aliqua voluptate nulla laboris consectetur dolore sunt nisi tempor ex velit proident reprehenderit aliquip laborum magna est duis ex id quis",
    "price": 496,
    "currency": "₹",
    "category": "organic",
    "img": "plant10.png",
    "size": "laborum",
    "plantType": "veniam",
    "height": 5,
    "humidity": 91,
    "waterEvery": "10 hr",
    "unit": 10,
    "rating": 3
  },
  {
    "id": 854,
    "title": "ut",
    "description": "magna id sunt deserunt et anim est occaecat aute aute nisi consequat anim culpa Lorem aliquip ad laborum anim nulla esse tempor amet occaecat deserunt incididunt qui Lorem veniam cillum id do dolore incididunt duis tempor sit commodo nisi non",
    "price": 467,
    "currency": "₹",
    "category": "organic",
    "img": "plant14.png",
    "size": "excepteur",
    "plantType": "ex",
    "height": 23,
    "humidity": 80,
    "waterEvery": "13 hr",
    "unit": 606,
    "rating": 5
  },
  {
    "id": 388,
    "title": "reprehenderit",
    "description": "dolore eiusmod in sint non velit quis et voluptate aliquip aliqua cupidatat duis cillum ad id dolor anim consectetur ad eu mollit quis et consequat elit ea nisi exercitation veniam in cupidatat nulla deserunt aliqua aliqua fugiat anim incididunt laboris",
    "price": 925,
    "currency": "₹",
    "category": "organic",
    "img": "plant17.png",
    "size": "fugiat",
    "plantType": "consequat",
    "height": 12,
    "humidity": 72,
    "waterEvery": "22 hr",
    "unit": 454,
    "rating": 5
  },
  {
    "id": 459,
    "title": "anim",
    "description": "in in labore eiusmod sit non aliqua deserunt excepteur nisi proident adipisicing labore fugiat consectetur excepteur cillum nulla minim cupidatat nisi reprehenderit aute elit in id voluptate minim non eu nisi do commodo minim in anim nisi voluptate nisi non",
    "price": 319,
    "currency": "₹",
    "category": "organic",
    "img": "plant1.png",
    "size": "officia",
    "plantType": "consectetur",
    "height": 8,
    "humidity": 55,
    "waterEvery": "13 hr",
    "unit": 622,
    "rating": 3
  },
  {
    "id": 338,
    "title": "quis",
    "description": "sint tempor adipisicing ullamco ut magna ad duis enim mollit consectetur occaecat non et consectetur aliquip Lorem incididunt excepteur anim in ex pariatur do ex ad dolor id Lorem in occaecat ex pariatur deserunt mollit tempor ullamco consequat esse nulla",
    "price": 915,
    "currency": "₹",
    "category": "organic",
    "img": "plant3.png",
    "size": "laborum",
    "plantType": "do",
    "height": 23,
    "humidity": 60,
    "waterEvery": "10 hr",
    "unit": 947,
    "rating": 3
  },
  {
    "id": 191,
    "title": "ipsum",
    "description": "amet fugiat consectetur ipsum ipsum do anim et ut occaecat irure commodo ipsum velit in voluptate esse nostrud aliqua reprehenderit adipisicing sunt ad ut officia cillum occaecat tempor commodo magna non occaecat exercitation aliquip eiusmod qui ex voluptate culpa Lorem",
    "price": 626,
    "currency": "₹",
    "category": "organic",
    "img": "plant4.png",
    "size": "reprehenderit",
    "plantType": "cillum",
    "height": 16,
    "humidity": 67,
    "waterEvery": "8 hr",
    "unit": 397,
    "rating": 2
  }
]
export default PLANTDATA;
