const PLANTDATA = [
  {
    "title": "Snake Plant",
    "description": "A low-maintenance plant with long, upright leaves that are usually green with yellow or white stripes.",
    "price": 250,
    "currency": "₹",
    "category": "succulent",
    "img": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhYZNg9Yjn_UpkpxWr08KJFCweFOm02_6M0C_LP1lamxyHErepGuVEWVRJrqQyVsAOu5hX_LQqyKU3yRfkp-JgvXPaUxrLv0zOHqKTVEYQSQDlZhdUulsx6wUcG23vkpLpFfxVvyNTJHlQ_Kzw4mc6m0nk-PHqmZBpI8RfTLWlC70MG2Z8X8K9RRzCyww/s400/Sansevieria_10-inch_1_400x-removebg-preview.png",
    "size": "medium",
    "plantType": "indoor",
    "height": 36,
    "humidity": 50,
    "waterEvery": "8",
    "unit": 30,
    "rating": 5
  },
  {
    "title": "Spider Plant",
    "description": " A resilient and versatile plant with long, narrow leaves that are usually green with white stripes.",
    "price": 220,
    "currency": "₹",
    "category": "hanging plant",
    "img": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiYaRmx-jFWh7odU0amTBwwKCd9DqSQXMY50_SJt7EIa-ZVUKmakt4uwi11Q2rl9D5H-wKVwgUSWyh4GP8O_YMm_x_D6ni3cu-vdqgQoCYKemNHdYct_fRcnAXHvrSuZRzVTTl9eTsx0nozEbNDS-cQqhEaEsxzFpWN97RjujK_R6lBt0tWTcreYnSgQA/s320/spider-plant-in-vase-removebg-preview.png",
    "size": "medium",
    "plantType": "indoor",
    "height": 18,
    "humidity": 60,
    "waterEvery": "8",
    "unit": 50,
    "rating": 4
  },
  {
    "title": "English Ivy",
    "description": "A classic and elegant plant with small, glossy leaves that can trail down from hanging baskets or climb up walls.",
    "price": 220,
    "currency": "₹",
    "category": "climbing plant",
    "img": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhdf_Y5quFDDkRsfBAY0yOa4v6Mq9BNjUoHZVvtz8zfIFncTFFNajz6_7EZSLzW7zYYErxg6n_VAuCbQU8jUXU2nejYMhskxMEHpC_C47T9v2Ocu2_c-Db1v3imy7Zk4UxDvckO4aIEsdI1lifOES-_8pO3wIdLbldRyUHj1AkgIyQz7XBaAPGTHO9A_Q/s320/50379762-removebg-preview.png",
    "size": "medium",
    "plantType": "indoor",
    "height": 8,
    "humidity": 60,
    "waterEvery": "8",
    "unit": 25,
    "rating": 3
  },
  {
    "title": "English Ivy",
    "description": "A classic and elegant plant with small, glossy leaves that can trail down from hanging baskets or climb up walls.",
    "price": 220,
    "currency": "₹",
    "category": "climbing plant",
    "img": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhdf_Y5quFDDkRsfBAY0yOa4v6Mq9BNjUoHZVvtz8zfIFncTFFNajz6_7EZSLzW7zYYErxg6n_VAuCbQU8jUXU2nejYMhskxMEHpC_C47T9v2Ocu2_c-Db1v3imy7Zk4UxDvckO4aIEsdI1lifOES-_8pO3wIdLbldRyUHj1AkgIyQz7XBaAPGTHO9A_Q/s320/50379762-removebg-preview.png",
    "size": "medium",
    "plantType": "indoor",
    "height": 8,
    "humidity": 60,
    "waterEvery": "8",
    "unit": 25,
    "rating": 3
  },
]
export default PLANTDATA;
